---
title: "\"My Pre-Registration\""
author: "Grace Manninen"
date: "2025-02-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

<details>

-   [Study Information](#study-information)
    -   [1. Title](#1-title)
    -   [2. Authors](#2-authors)
    -   [3. Description](#3-description)
    -   [4. Hypotheses](#4-hypotheses)
-   [Design Plan](#design-plan)
    -   [5. Study type](#5-study-type)
    -   [6. Blinding](#6-blinding)
    -   [7. Is there any additional blinding in this study?](#7-is-there-any-additional-blinding-in-this-study-)
    -   [8. Study design](#8-study-design)
    -   [9. Randomization](#9-randomization)
-   [Sampling Plan](#sampling-plan)
    -   [10. Existing data](#10-existing-data)
    -   [11. Explanation of existing data](#11-explanation-of-existing-data)
    -   [12. Data collection procedures](#12-data-collection-procedures)
    -   [13. Sample size](#13-sample-size)
    -   [14. Sample size rationale](#14-sample-size-rationale)
    -   [15. Stopping rule](#15-stopping-rule)
-   [Variables](#variables)
    -   [16. Manipulated variables](#16-manipulated-variables)
    -   [17. Measured variables](#17-measured-variables)
    -   [18. Indices](#18-indices)
-   [Analysis Plan](#analysis-plan)
    -   [19. Statistical models](#19-statistical-models)
    -   [20. Transformations](#20-transformations)
    -   [21. Inference criteria](#21-inference-criteria)
    -   [22. Data exclusion](#22-data-exclusion)
    -   [23. Missing data](#23-missing-data)
    -   [24. Exploratory analysis](#24-exploratory-analysis)
-   [Other](#other)
    -   [25. Other](#25-other)

</details>

# Study Information 

## 1. Title 

Serial dependence on perceptual categorization of animals for animal conservation

## 2. Authors 

Grace Manninen

## 3. Description 

Our brains use serial dependence to influence how we percieve and judge incoming stimuli. Serial dependence seems to influence even high level stimuli, like human faces. Therefor it is seen that previous stimuli, impacts how present stimuli is judged. [@StJohn-Saaltink2015SerialDependence]
I want to look at if previous images, of categorically known positive or negatively viewed animals, impacts how positively or negatively present stimuli of animals are. It is seen that animals are able to be categorized into groups. Such as, fear evoking animals are crocodiles, bears, lions, tigers, snakes, etc. Disgust is triggered by often paracitic and small animals, like rats, cockroaches, ticks, etc., [@Polak2020Scaryandnastybeasts]. Our right amydala is speciallized at processing visual information about animals [@mormann2011Acategory-specific]
So our brains are speciallized at recognizing animals [@mormann2011Acategory-specific]. The amygdala is where fear-generating stimuli is processed, and these emotions of fear help to react towards something posing risk to your life. So animals that have evolutionary posed a risk to life, like large predators are seen as scarier [@Castillo2020TheImportanceofHumanEmotionsforWildlifeConservation]. I want to see if previous stimuli that is pleasent, such as a red panda [@Polak2020Scaryandnastybeasts], will cause present stimuli that is scary or gross, such as a snake or tape worm [@Polak2020Scaryandnastybeasts], appear more pleasent, based on the serial dependence theory [@StJohn-Saaltink2015SerialDependence]. This will help in wildlife conservation, if you are able to make animals that are seen as scary, or gross, appear more likeable [@Lindall2019Messagingmatters]. There is even the possibility if you are able to make dogs that don't seem as asthetically pleasing, more likeable, then they may be adopted more [@Borgi2016PetFace].


## 4. Hypotheses 

Previously presented stimuli of a well-known liked animal, will cause present stimuli of a not-as well-liked, or scary, or gross animal appear more likeable.

# Design Plan 

In this experiment, it will be a computer based experiment.
The first block, the participants will be presented with a well-liked animal on the screen for 10 seconds (arbitrary number-need to figure out the exact time). Then after, a not-as well-liked, or scary, or gross animal will appear on the screen, and the participant will be asked to rank that animals: how much they like that animal, its scariness, its grossness.
The second block, to compare if serial dependence plays a role in animal perception and judgement, the a not-as well-liked, or scary, or gross animal will appear on the screen, without any previous stimuli before, and will be asked to rank that animals: how much they like that animal, its scariness, its grossness.

## 5. Study type 

This study will be an observational study where data is collected from random participants. The data collected can be from any sociocultural background, as differences in sociocultural background doesn't seem to drive judgement of animal categories [@Albert2018thetwentymost]. It will be a computer based experiment, so that anyone, from anywhere, can access it and complete it. It will be a natural experiment. 

## 6. Blinding 

The participants will be blinded. They will not know ahead of time if they are in the first or second block, or what the purpose of the study is. They will simply be asked to will be asked to rank that animals: how much they like that animal, its scariness, its grossness.
Researcher will be blinded. Researcher will not interact directly with participants. When researcher is analyzing data they will not see what block participants where in.



- human subjects will not know the treatment group to which they have been assigned.

- Personnel who analyze the data collected from the study are not aware of the treatment applied to any given group.

## 7. Is there any additional blinding in this study? 

no

## 8. Study design 



## 9. Randomization 


# Sampling Plan 



## 10. Existing data 

yes 
[@Albert2018thetwentymost]
[@Erin2024Effectsofrelational]
etc 
all look at how animals are viewed and percieved


## 11. Explanation of existing data 



## 12. Data collection procedures 


## 13. Sample size 


## 14. Sample size rationale 


## 15. Stopping rule 


# Variables 

- what animal 
- scaryness scale
- grossness scale 
- how well liked scale 
- block 1 or block 2 
## 16. Manipulated variables 

- block 1 or block 2 to test for serial dependence


## 17. Measured variables 

- scaryness scale
- grossness scale 
- how well liked scale 



## 18. Indices 


# Analysis Plan 


## 19. Statistical models 


## 20. Transformations 


## 21. Inference criteria 



## 22. Data exclusion 

-if they answer to quickly (less than 5 seconds) then discarded, as might not be paying attention to experiment


## 23. Missing data 

- missing data can be kept, as three diff variables are being measured 


## 24. Exploratory analysis 



# Other 

## 25. Other 

> **(Optional)** If there is any additional information that you feel needs to be included in your preregistration, please enter it here. 

# References

New, J., Cosmides, L., Tooby, J. (2007). Category-specific attention for animals reflects ancestral priorities, not expertise. PNAS, 104, 16598-16603. https://doi.org/10.1073pnas.0703913104 
Florian Mormann1–3, J. D., Simon Kornblith1, , Milica Milosavljevic1, M. C., 2, Matias Ison2,4, , Naotsugu Tsuchiya1, A. K., 5, Rodrigo Quian Quiroga1,4, , & Ralph Adolphs1, I. F., 6 & Christof Koch1,7. (2011). A category-specific response
to animals in the right
human amygdala. nature neuroscience, 14(10). https://doi.org/10.1038/nn.2899 
Erin B. Allison1, E. N. T., Zackary A. GrahamID1, Melissa Amarello3, Jeffrey J. SmithID3,4, Zachary J. Loughman1*. (2024). Effects of relational and instrumental messaging on human perception of rattlesnakes. PLoS ONE(19(4)). https://doi.org/10.1371/journal.pone.0298737
Castillo-Huitrón NM, N. E., Santos-Fita D and Estrada-Lugo E. (2020). The Importance of Human Emotions for Wildlife Conservation. Front. Psychol, 11(1277). https://doi.org/ https://doi.org/10.3389/fpsyg.2020.01277 
Lindall R. Kidda, b., ⁎, Georgia E. Garrarda,b, Sarah A. Bekessya,b,c, Morena Millsd,, & Adrian R. Camillerie, F. F., Kelly S. Fieldingg, Ascelin Gordona, Emily A. Gregga,b, Alexander M. Kusmanoffa,b,c, Winnifred Louish, Katie Mooni, Jenny A. Robinsonj, Matthew J. Selinskea,c, Danielle Shanahank, Vanessa M. Adamsl. (2019). Messaging matters: A systematic review of the conservation messaging T literature. Elsevier, 236(Biological Conservatio), 92-99. 
Marta Borgi, F. C. (2016). Pet Face: Mechanisms Underlying Human-Animal Relationships. 
Jakub Polak1, Silvie Radlova1, Marketa Janovcova1,3, Jaroslav Flegr1, Eva Landova1,3* and Daniel Frynta1,3. (2020). Scary and nasty beasts: Self-reported fear and disgust of common phobic animals. British Journal of Psychology, 111, 297-321.
St John-Saaltink, E. K., Peter ; Lau, Hakwan C ; de Lange, Floris P. (2015). Serial Dependence in Perceptual Decisions Is Reflected in Activity Patterns in Primary Visual Cortex. The Journal of neuroscience, 36, 6186-6192. https://doi.org/10.1523/JNEUROSCI.4390-15.2016 
Julien Troudet1, P. G., Amandine Blin2, Régine Vignes-Lebbe1 & Frédéric Legendre. (2017). Taxonomic bias in biodiversity data and societal preferences. scientific reports, 7. https://doi.org/10.1038/s41598-017-09084-6 
Albert C, L. G., Courchamp F. (2018). The twenty most charismatic species. PLoS ONE, 13( e0199149). https://doi.org/https://doi.org/10.1371/journal.pone.0199149 



